version: '3.8'

services:
  mariadb:
    image: imagen-mariadb:16
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
