version: '3'
services:
  myapp:
    image: imagen_nodejs:18.0
    container_name: myapp-container
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["node", "app.js"]
    # Uncomment the following lines if you want the container to stay running
    #command: ["sh", "-c", "python app.py && tail -f /dev/null"]